name: CI
on:  [workflow_dispatch, pull_request, push]

env:
  EXAMPLE_DATA_PATH: /home/runner/example_data/

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download data
        run: |
          cd $HOME
          curl https://zenodo.org/record/8143110/files/example_data.tar.gz -o example_data.tar.gz
          tar xzf example_data.tar.gz
      - uses: fastai/workflows/nbdev3-ci@master
